[package]
name = "queuecheck"
edition = "2024.beta" # Kita pertahankan edisi terbaru ini

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "testnet" }

[addresses]
queuecheck = "0x0"